name: Deno Check Every 5min

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  check-deno:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: Check Deno version
        run: deno --version